/* Hand-authored, difficulty-graded relation items (depth of vocabulary knowledge).
   type: syn (同义/反义) · analogy (类比) · classify (分类/找不同)
   lvl 1–5 = difficulty. words[] = the vocab word(s) tested → feed mastery.
   unit: a unit number, or 0 / omitted for cross-unit items.
   Distractors are chosen by hand for plausibility. Answer is a 0-based index. */
window.RELATIONS = { version:1, items:[

/* ============ 同义 / 反义 (synonym / antonym) ============ */
{id:"syn-01",type:"syn",ask:"同义词",lvl:2,unit:1,words:["intelligent"],
 stem:"与 <b>intelligent</b>（聪明的）意思<b>最接近</b>的是：",options:["clever","lazy","tiny","silver"],answer:0,
 explain:"intelligent ≈ clever 聪明的。"},
{id:"syn-02",type:"syn",ask:"同义词",lvl:3,unit:1,words:["talented"],
 stem:"与 <b>talented</b> 意思<b>最接近</b>的是：",options:["gifted","foreign","empty","ancient"],answer:0,
 explain:"talented ≈ gifted 有天赋的。"},
{id:"syn-03",type:"syn",ask:"反义词",lvl:2,unit:6,words:["empty"],
 stem:"与 <b>empty</b>（空的）意思<b>相反</b>的是：",options:["full","open","dark","quiet"],answer:0,
 explain:"empty ↔ full 满的。"},
{id:"syn-04",type:"syn",ask:"反义词",lvl:2,unit:6,words:["enemy"],
 stem:"与 <b>enemy</b>（敌人）意思<b>相反</b>的是：",options:["friend","soldier","captain","author"],answer:0,
 explain:"enemy ↔ friend 朋友。"},
{id:"syn-05",type:"syn",ask:"反义词",lvl:3,unit:6,words:["victory"],
 stem:"与 <b>victory</b> 意思<b>相反</b>的是：",options:["defeat","prize","battle","journey"],answer:0,
 explain:"victory 胜利 ↔ defeat 失败。"},
{id:"syn-06",type:"syn",ask:"同义词",lvl:3,unit:5,words:["nervous","anxious"],
 stem:"与 <b>nervous</b> 意思<b>最接近</b>的是：",options:["anxious","calm","brave","proud"],answer:0,
 explain:"nervous ≈ anxious 紧张/焦虑的。"},
{id:"syn-07",type:"syn",ask:"同义词",lvl:3,unit:8,words:["faithful"],
 stem:"与 <b>faithful</b> 意思<b>最接近</b>的是：",options:["loyal","cruel","lazy","lonely"],answer:0,
 explain:"faithful ≈ loyal 忠诚的。"},
{id:"syn-08",type:"syn",ask:"反义词",lvl:2,unit:6,words:["succeed","fail"],
 stem:"与 <b>succeed</b>（成功）意思<b>相反</b>的是：",options:["fail","win","beat","try"],answer:0,
 explain:"succeed ↔ fail 失败。"},
{id:"syn-09",type:"syn",ask:"反义词",lvl:3,unit:5,words:["accept"],
 stem:"与 <b>accept</b> 意思<b>相反</b>的是：",options:["refuse","agree","receive","keep"],answer:0,
 explain:"accept 接受 ↔ refuse 拒绝。"},
{id:"syn-10",type:"syn",ask:"同义词",lvl:2,unit:5,words:["lonely"],
 stem:"与 <b>lonely</b>（孤独的）意思<b>最接近</b>的是：",options:["alone","happy","busy","proud"],answer:0,
 explain:"lonely ≈ alone 孤单的。"},
{id:"syn-11",type:"syn",ask:"同义词",lvl:3,unit:3,words:["major"],
 stem:"与 <b>major</b> 意思<b>最接近</b>的是：",options:["main","minor","equal","tiny"],answer:0,
 explain:"major ≈ main 主要的（↔ minor）。"},
{id:"syn-12",type:"syn",ask:"同义词",lvl:3,unit:5,words:["grateful"],
 stem:"与 <b>grateful</b> 意思<b>最接近</b>的是：",options:["thankful","careless","hopeless","painful"],answer:0,
 explain:"grateful ≈ thankful 感激的。"},
{id:"syn-13",type:"syn",ask:"反义词",lvl:3,unit:8,words:["attack"],
 stem:"与 <b>attack</b>（攻击）意思<b>相反</b>的是：",options:["defend","hide","press","pull"],answer:0,
 explain:"attack ↔ defend 防守。"},
{id:"syn-14",type:"syn",ask:"同义词",lvl:2,unit:3,words:["tiny"],
 stem:"与 <b>tiny</b>（极小的）意思<b>最接近</b>的是：",options:["small","huge","tall","wide"],answer:0,
 explain:"tiny ≈ small 小的（↔ huge）。"},
{id:"syn-15",type:"syn",ask:"反义词",lvl:3,unit:5,words:["unfamiliar"],
 stem:"与 <b>unfamiliar</b> 意思<b>相反</b>的是：",options:["familiar","strange","foreign","unknown"],answer:0,
 explain:"unfamiliar 陌生的 ↔ familiar 熟悉的。"},

/* ============ 类比 (analogy) ============ */
{id:"ana-01",type:"analogy",lvl:3,unit:1,words:["artist"],
 stem:"类比：<b>artist : paint</b> :: <b>writer : ?</b>",options:["write","read","sing","count"],answer:0,
 explain:"人 : 该做的事。artist→paint，writer→write。"},
{id:"ana-02",type:"analogy",lvl:3,unit:4,words:["wheel","wing"],
 stem:"类比：<b>wheel : car</b> :: <b>wing : ?</b>",options:["plane","road","sky","engine"],answer:0,
 explain:"部分 : 整体。wheel 属于 car，wing 属于 plane。"},
{id:"ana-03",type:"analogy",lvl:3,unit:6,words:["soldier"],
 stem:"类比：<b>soldier : army</b> :: <b>player : ?</b>",options:["team","school","office","shop"],answer:0,
 explain:"成员 : 群体。soldier 属于 army，player 属于 team。"},
{id:"ana-04",type:"analogy",lvl:3,unit:6,words:["victory"],
 stem:"类比：<b>victory : happy</b> :: <b>defeat : ?</b>",options:["sad","proud","calm","brave"],answer:0,
 explain:"事件 : 心情。victory→happy，defeat→sad。"},
{id:"ana-05",type:"analogy",lvl:3,unit:6,words:["enemy"],
 stem:"类比：<b>day : night</b> :: <b>enemy : ?</b>",options:["friend","soldier","king","author"],answer:0,
 explain:"反义关系。day↔night，enemy↔friend。"},
{id:"ana-06",type:"analogy",lvl:3,unit:6,words:["author"],
 stem:"类比：<b>author : book</b> :: <b>painter : ?</b>",options:["painting","song","film","poem"],answer:0,
 explain:"创作者 : 作品。author→book，painter→painting。"},
{id:"ana-07",type:"analogy",lvl:3,unit:3,words:["tiny"],
 stem:"类比：<b>big : huge</b> :: <b>small : ?</b>",options:["tiny","wide","short","heavy"],answer:0,
 explain:"程度递进。big→huge（更大），small→tiny（更小）。"},
{id:"ana-08",type:"analogy",lvl:4,unit:4,words:["petrol"],
 stem:"类比：<b>petrol : car</b> :: <b>food : ?</b>",options:["body","wheel","road","sky"],answer:0,
 explain:"能量来源 : 使用者。汽油驱动汽车，食物滋养身体(body)。"},

/* ============ 分类 / 找不同 (classification / odd-one-out) ============ */
{id:"cls-01",type:"classify",lvl:2,unit:0,words:["balloon"],
 stem:"选出与其他<b>不同类</b>的一个：",options:["dinosaur","tiger","ant","balloon"],answer:3,
 explain:"dinosaur/tiger/ant 都是动物，balloon 是交通/物品。"},
{id:"cls-02",type:"classify",lvl:3,unit:0,words:["onion"],
 stem:"选出与其他<b>不同类</b>的一个：",options:["wheel","petrol","balloon","onion"],answer:3,
 explain:"wheel/petrol/balloon 与交通有关，onion（洋葱）是食物。"},
{id:"cls-03",type:"classify",lvl:2,unit:0,words:["budget"],
 stem:"选出<b>不表示情绪/感受</b>的一个：",options:["nervous","lonely","grateful","budget"],answer:3,
 explain:"nervous/lonely/grateful 都是感受，budget（预算）不是。"},
{id:"cls-04",type:"classify",lvl:2,unit:0,words:["soldier"],
 stem:"选出与其他<b>不同类</b>的一个：",options:["app","download","network","soldier"],answer:3,
 explain:"app/download/network 与科技网络有关，soldier（士兵）不是。"},
{id:"cls-05",type:"classify",lvl:3,unit:0,words:["victory"],
 stem:"选出与其他<b>不同类</b>的一个：",options:["artist","artistic","original","victory"],answer:3,
 explain:"artist/artistic/original 与艺术有关，victory（胜利）与战争有关。"},
{id:"cls-06",type:"classify",lvl:2,unit:0,words:["chopstick"],
 stem:"选出与其他<b>不同类</b>的一个：",options:["budget","per cent","count","chopstick"],answer:3,
 explain:"budget/per cent/count 与数字数据有关，chopstick（筷子）不是。"},
{id:"cls-07",type:"classify",lvl:2,unit:0,words:["laptop"],
 stem:"选出与其他<b>不同类</b>的一个：",options:["soldier","enemy","victory","laptop"],answer:3,
 explain:"soldier/enemy/victory 与战争有关，laptop（笔记本电脑）不是。"},
{id:"cls-08",type:"classify",lvl:3,unit:0,words:["soldier"],
 stem:"选出<b>不属于「学习/记忆」</b>话题的一个：",options:["diet","repeat","summary","soldier"],answer:3,
 explain:"diet/repeat/summary 与学习记忆有关，soldier 属于历史战争。"},
{id:"cls-09",type:"classify",lvl:3,unit:0,words:["diet"],
 stem:"选出与其他<b>不同类</b>的一个：",options:["balloon","wheel","petrol","diet"],answer:3,
 explain:"balloon/wheel/petrol 与交通有关，diet（饮食）不是。"},
{id:"cls-10",type:"classify",lvl:1,unit:0,words:["balloon"],
 stem:"下面哪个词与<b>交通 / 出行</b>有关？",options:["balloon","dinosaur","onion","editor"],answer:0,
 explain:"balloon（热气球）是一种出行方式。"},
{id:"cls-11",type:"classify",lvl:1,unit:0,words:["soldier"],
 stem:"下面哪个词与<b>历史 / 战争</b>有关？",options:["soldier","laptop","onion","budget"],answer:0,
 explain:"soldier（士兵）与战争有关。"},
{id:"cls-12",type:"classify",lvl:2,unit:0,words:["balloon"],
 stem:"选出与其他<b>不同类</b>的一个：",options:["faithful","servant","queen","balloon"],answer:3,
 explain:"faithful/servant/queen 出自「动物与责任/宫廷」话题，balloon 属于交通。"},

/* ---- expansion ---- */
{id:"syn-16",type:"syn",ask:"反义词",lvl:2,unit:6,words:["hide"],
 stem:"与 <b>hide</b>（躲藏）意思<b>相反</b>的是：",options:["show","cover","keep","fill"],answer:0,explain:"hide 藏 ↔ show 展示。"},
{id:"syn-17",type:"syn",ask:"反义词",lvl:3,unit:6,words:["fill"],
 stem:"与 <b>fill</b>（装满）意思<b>相反</b>的是：",options:["empty","open","close","pull"],answer:0,explain:"fill 装满 ↔ empty 倒空。"},
{id:"syn-18",type:"syn",ask:"反义词",lvl:2,unit:2,words:["go up"],
 stem:"与 <b>go up</b>（上升）意思<b>相反</b>的是：",options:["go down","write down","take place","come out"],answer:0,explain:"go up ↔ go down 下降。"},
{id:"syn-19",type:"syn",ask:"反义词",lvl:2,unit:2,words:["agree"],
 stem:"与 <b>agree</b>（同意）意思<b>相反</b>的是：",options:["disagree","reply","wonder","count"],answer:0,explain:"agree ↔ disagree 不同意。"},
{id:"syn-20",type:"syn",ask:"同义词",lvl:2,unit:7,words:["relax"],
 stem:"与 <b>relax</b>（放松）意思<b>最接近</b>的是：",options:["rest","work","study","hurry"],answer:0,explain:"relax ≈ rest 休息。"},
{id:"syn-21",type:"syn",ask:"同义词",lvl:3,unit:7,words:["stressed"],
 stem:"与 <b>stressed</b> 意思<b>最接近</b>的是：",options:["worried","calm","proud","glad"],answer:0,explain:"stressed ≈ worried 焦虑的。"},
{id:"syn-22",type:"syn",ask:"同义词",lvl:3,unit:7,words:["normal"],
 stem:"与 <b>normal</b> 意思<b>最接近</b>的是：",options:["usual","strange","special","rare"],answer:0,explain:"normal ≈ usual 平常的。"},
{id:"syn-23",type:"syn",ask:"同义词",lvl:2,unit:4,words:["notice"],
 stem:"与 <b>notice</b>（注意到）意思<b>最接近</b>的是：",options:["see","hide","press","pull"],answer:0,explain:"notice ≈ see 看到、注意到。"},
{id:"ana-09",type:"analogy",lvl:3,unit:1,words:["editor"],
 stem:"类比：<b>teacher : teach</b> :: <b>editor : ?</b>",options:["edit","write","read","print"],answer:0,explain:"职业 : 该做的事。teacher→teach，editor→edit。"},
{id:"ana-10",type:"analogy",lvl:3,unit:6,words:["captain"],
 stem:"类比：<b>captain : soldiers</b> :: <b>teacher : ?</b>",options:["students","books","school","lessons"],answer:0,explain:"领导 : 被带领者。captain→soldiers，teacher→students。"},
{id:"ana-11",type:"analogy",lvl:3,unit:6,words:["empty"],
 stem:"类比：<b>full : empty</b> :: <b>happy : ?</b>",options:["sad","glad","calm","proud"],answer:0,explain:"反义关系。full↔empty，happy↔sad。"},
{id:"ana-12",type:"analogy",lvl:3,unit:4,words:["heat"],
 stem:"类比：<b>heat : hot</b> :: <b>cool : ?</b>",options:["cold","warm","wet","dry"],answer:0,explain:"动作 : 结果状态。heat→hot，cool→cold。"},
{id:"cls-13",type:"classify",lvl:2,unit:0,words:["summary"],
 stem:"选出<b>不表示感受</b>的一个：",options:["lonely","grateful","nervous","summary"],answer:3,explain:"lonely/grateful/nervous 是感受，summary（总结）不是。"},
{id:"cls-14",type:"classify",lvl:1,unit:0,words:["repeat"],
 stem:"下面哪个词与<b>学习 / 记忆</b>有关？",options:["repeat","soldier","balloon","onion"],answer:0,explain:"repeat（重复）与学习记忆有关。"},
{id:"cls-15",type:"classify",lvl:1,unit:0,words:["artist"],
 stem:"下面哪个词与<b>艺术</b>有关？",options:["artist","soldier","petrol","budget"],answer:0,explain:"artist（艺术家）与艺术有关。"},
{id:"cls-16",type:"classify",lvl:2,unit:0,words:["chopstick"],
 stem:"选出与其他<b>不同类</b>的一个：",options:["balloon","wheel","petrol","chopstick"],answer:3,explain:"balloon/wheel/petrol 与交通有关，chopstick（筷子）不是。"},
{id:"cls-17",type:"classify",lvl:2,unit:0,words:["onion"],
 stem:"选出与其他<b>不同类</b>的一个：",options:["laptop","screen","software","onion"],answer:3,explain:"laptop/screen/software 与科技有关，onion 是食物。"},
{id:"cls-18",type:"classify",lvl:2,unit:0,words:["laptop"],
 stem:"选出与其他<b>不同类</b>的一个：",options:["soldier","enemy","captain","laptop"],answer:3,explain:"soldier/enemy/captain 与战争有关，laptop 不是。"},
{id:"cls-19",type:"classify",lvl:1,unit:0,words:["budget"],
 stem:"下面哪个词与<b>数字 / 数据</b>有关？",options:["budget","dinosaur","onion","balloon"],answer:0,explain:"budget（预算）与数字数据有关。"},
{id:"cls-20",type:"classify",lvl:2,unit:0,words:["petrol"],
 stem:"选出与其他<b>不同类</b>的一个：",options:["tiger","ant","dinosaur","petrol"],answer:3,explain:"tiger/ant/dinosaur 是动物，petrol（汽油）不是。"}

],

/* ====== 词语联想 Word Associates (pick the related words) ======
   target + 4 correct associates + 4 distractors. lvl = difficulty. */
wat:[
 {id:"wat-01",lvl:3,unit:7,target:"diet",correct:["food","healthy","eat","balanced"],distractors:["pencil","river","engine","silver"],explain:"diet 与 食物/健康/吃/均衡 相关。"},
 {id:"wat-02",lvl:3,unit:6,target:"victory",correct:["win","celebrate","army","battle"],distractors:["onion","laptop","garden","pencil"],explain:"victory 与 赢/庆祝/军队/战斗 相关。"},
 {id:"wat-03",lvl:3,unit:1,target:"artist",correct:["paint","picture","museum","draw"],distractors:["petrol","wheel","budget","ant"],explain:"artist 与 画/图画/博物馆/绘画 相关。"},
 {id:"wat-04",lvl:3,unit:3,target:"traffic",correct:["car","road","jam","busy"],distractors:["apple","moon","song","king"],explain:"traffic 与 汽车/道路/堵塞/繁忙 相关。"},
 {id:"wat-05",lvl:3,unit:5,target:"nervous",correct:["afraid","worried","exam","shaking"],distractors:["happy","apple","wheel","river"],explain:"nervous 与 害怕/担心/考试/发抖 相关。"},
 {id:"wat-06",lvl:3,unit:3,target:"download",correct:["app","Internet","file","phone"],distractors:["onion","garden","king","wheel"],explain:"download 与 应用/网络/文件/手机 相关。"},
 {id:"wat-07",lvl:3,unit:6,target:"soldier",correct:["army","fight","war","gun"],distractors:["flower","cake","piano","budget"],explain:"soldier 与 军队/战斗/战争/枪 相关。"},
 {id:"wat-08",lvl:3,unit:8,target:"faithful",correct:["loyal","dog","friend","trust"],distractors:["tiny","purple","engine","onion"],explain:"faithful 与 忠诚/狗/朋友/信任 相关。"},
 {id:"wat-09",lvl:3,unit:7,target:"summary",correct:["short","main","points","text"],distractors:["river","tiger","wheel","apple"],explain:"summary 与 简短/要点/主要/文章 相关。"},
 {id:"wat-10",lvl:3,unit:4,target:"balloon",correct:["air","fly","float","party"],distractors:["pencil","army","budget","onion"],explain:"balloon 与 空气/飞/漂浮/聚会 相关。"},
 {id:"wat-11",lvl:3,unit:2,target:"budget",correct:["money","plan","spend","limit"],distractors:["tiger","cloud","paint","wing"],explain:"budget 与 钱/计划/花费/限额 相关。"},
 {id:"wat-12",lvl:3,unit:5,target:"exchange",correct:["swap","student","culture","visit"],distractors:["onion","wheel","silver","ant"],explain:"exchange 与 交换/学生/文化/访问 相关。"}
],

/* ====== 是非快筛 Yes/No — real words come from the vocab; these are fakes ====== */
pseudo:["florp","snurd","blint","quomp","gwisp","threll","skabe","vondle","dworl","flen","snotch","plimf","gruve","chask","drilp","frentle","snorp","twemp","klint","spragg","thurm","veeb","morpe","blorn","crelt","dwomp","frisby","glunt","prisk","snive"]
};
